apiVersion: v1
kind: Service
metadata:
  name: novostack2-coll-f171081ae31a49d88670d9693e1d54a3-srv
spec:
  selector:
    app: novostack2-coll-f171081ae31a49d88670d9693e1d54a3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9020
  type: ClusterIP